--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/python:3.7"
  steps: 
    - checkout
    - 
      run: 
        command: "python3 -m venv venv - venv/bin/activate pip install -r requirements.txt"
        name: "install dependencies"
    - 
      run: 
        command: ". venv/bin/activate flake8 --exclude=env* --statitics pytest --jumixml-test-results/junit.xml"
        name: "run tests"
    - 
      store_test_results: 
        path: test-results
  working_directory: ~/devops2
version: 2
