#Python CircleCI 2.0 configuration file
version: 2
jobs:
     build:
           docker:
                  - image: circleci/python:3.7

           working_directory: ~/devops
         
           steps:
#1 Obtener el repositorio de GitHub.
           - checkout
#2 Crear un entorno virtual e instalar las dependecias.
           -run:
                name: install dependencies
                command: |
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
#3 Ejecutar el software de convenciones de codificación más el tester.
           -run:
              name: run tests
              command: |
                        . venv/bin/activate
                        flake8 –-exclude=venv* --statistics
# pytest -v –-cov=calculator
                        pytest –-junitxml=test-results/junit.xml
           - store_test_results:
                path: test-results